### ISSUE TITLE
WPTranslationDay2021

### ISSUE THREAD

**Issue by abhansnuk** [wpmarketingteam/Marcomms-Polyglots#1]

**Comment by abhansnuk** [comment]
For adding to potential task list and sharing at Marketing meetings, requested info from Erica on polyglots/ WPTD to:
- better understand what additional support may be needed from the marketing team during the event itself (in addition to those joining the organizers)
- if any additional recruitment needs to be shared via the marketing team meetings
- checking how Marketing Team members expressing an interest can get involved in WPTD. Do all polyglot and marketing team members need to get involved via the translation day slack rather than through the make team meetings? If so, should we be directing people to join the translation slack if they want to see and share thoughts on the marcomms related conversations? 
- requested update from WPTD if relevant to marketing team meeting on 18 or 25 August

**Comment by murillol** [comment]
Tasks

- [ ] Create social media posts from [informational post,](https://docs.google.com/document/d/1LomTWGUwLdluOgKpaluJtZYfQbddy6YEUOeugp1mWAg/edit#heading=h.x4n99jq48j03) once all details confirmed  

- Use [this sheet](https://docs.google.com/spreadsheets/d/1-v_qR3_VN31phtMK8PCCqsSbVXLMuFOQopNtcKfz1Ms/edit#gid=0) to schedule social

**Comment by murillol** [comment]
**Tasks**

- [ ] Adapt graphic to blocks of four, asking Nok or Boy for help on this
- [ ] Contact in order of the blocks of four
- [ ] List who from the WPTD team is contacting the nominees
- [ ] Template for contacting nominees on Slack (@murillol)
- [ ] Create Form (Felipe S), get email addresses from the WP.org ID 
- [ ] Ask Erica for password to the gmail to send these out (@abhansnuk)
- [ ] Extend the nomination deadline to 30 September 2021 
- [ ] Update nominations post (@abhansnuk)
